// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI6wj65595dnCsxslt48aG0EZfGWtZBz0',
    appId: '1:757843401159:web:032c56ed6baf3f719c61e2',
    messagingSenderId: '757843401159',
    projectId: 'ulearningapp-2d5b3',
    authDomain: 'ulearningapp-2d5b3.firebaseapp.com',
    storageBucket: 'ulearningapp-2d5b3.appspot.com',
    measurementId: 'G-YSWXDGDMZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhjQto12mxngfpEWGo37D9KWvS9-ML9h8',
    appId: '1:757843401159:android:c0700d4af6ef86ca9c61e2',
    messagingSenderId: '757843401159',
    projectId: 'ulearningapp-2d5b3',
    storageBucket: 'ulearningapp-2d5b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3t5SuoyWV7HJByp_mEtwnK3feeOX4d9M',
    appId: '1:757843401159:ios:825d106eadadda9e9c61e2',
    messagingSenderId: '757843401159',
    projectId: 'ulearningapp-2d5b3',
    storageBucket: 'ulearningapp-2d5b3.appspot.com',
    iosBundleId: 'com.example.ulearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3t5SuoyWV7HJByp_mEtwnK3feeOX4d9M',
    appId: '1:757843401159:ios:70dfe63ddf0a479d9c61e2',
    messagingSenderId: '757843401159',
    projectId: 'ulearningapp-2d5b3',
    storageBucket: 'ulearningapp-2d5b3.appspot.com',
    iosBundleId: 'com.example.ulearningApp.RunnerTests',
  );
}
